### ISSUE TITLE
Issue with b1correct

### ISSUE THREAD

**Issue by RP-HAO** [NYU-DiffusionMRI/DESIGNER-v2#12]
Dear DESIGNER team,

Thank you very much for developing and maintaining this extremely useful processing pipeline.

My first (and main) question is about using option _-b1correct_ for bias field correction. While running via docker I kept getting an error message as attached below:
<img width="1903" alt="Screen Shot 2024-07-26 at 22 54 48" src="https://github.com/user-attachments/assets/353ed80f-e1c5-4b67-a059-a0d278535086">
I tried both on a Mac and a Windows and got the same error. May I ask if there's something wrong/missing with my installation, or could it be something else?

Another minor point is regarding printing the messages: when I try to input several commands (e.g., picture below used _degibbs_ and _ants_motion_correction_), the outputs from _run.command_ can always be printed in real time, whereas outputs from _print_ function get delayed, with an example being:
<img width="1653" alt="Screen Shot 2024-07-26 at 23 02 48" src="https://github.com/user-attachments/assets/b5214b1f-9a66-433d-bcb1-cb17f9813d37">
While this doesn't affect any underlying image processings, having all output messages flushed in real time could be pretty informative when the pipeline takes very long to run. Would this be possible?

Best,
Runpu

**Comment by jchen33344** [comment]
Hello Runpu,

Thank you for your feedback. Since b1correct is not part of the default DESIGNER pipeline, we did not include ANTs as a dependency in docker. However, you are free to use the dev tools on Docker to add ANTs if you are comfortable.

I am not sure I am understanding the suggested improvement. When I run it on docker, the output from print seems to be in real time.
![Screenshot 2024-07-30 at 3 47 02 PM](https://github.com/user-attachments/assets/a974e766-fed2-44fd-9c27-20ee0a0d86c2)
We also welcome you to send a pull request to suggest the change and we can test these changes.

Best,
Jenny

**Comment by RP-HAO** [comment]
Hi Jenny,

Thanks for the info on b1correct!

My problem with not having output from print in real time seems to be related to the output buffering in python. I was able to solve it by running docker command with an additional environment variable _-e PYTHONUNBUFFERED=1_. :) Thanks again!

Best,
Runpu
